import {
    Card
} from "@/components/ui/card"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faReply } from '@fortawesome/free-solid-svg-icons'
import React from 'react'

export default function AiSuggest({aidescription}) {
    return (
        <Card className="my-5 w-full h-[305px] p-3 flex flex-col">
            <p className="text-sm text-slate-600 font-medium pb-1 border-b-[1px]">This content is generated by AI.</p>
            <div className="mt-2 overflow-y-auto">
                <p className="text-[13px] text-black">
                    {aidescription}
                </p>
            </div>
        </Card>
    )
}
