import {
    Card
} from "@/components/ui/card"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faReply } from '@fortawesome/free-solid-svg-icons'
import React from 'react'

export default function AiSuggest() {
    return (
        <Card className="my-5 w-full h-[305px] p-3 flex flex-col">
            <p className="text-sm text-slate-600 font-medium pb-1 border-b-[1px]">This content is generated by AI.</p>
            <div className="mt-2 overflow-y-auto">
                <p className="text-[13px] text-black">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum reiciendis mollitia odit suscipit eius aperiam tenetur ipsa dolores enim, architecto quaerat exercitationem cumque quod numquam atque deserunt doloremque magni aut maiores ad. Inventore neque repudiandae tenetur doloremque minus ullam laborum magni sit, nemo nesciunt. Nobis quas, explicabo molestias ipsam illo, iusto unde sunt, illum saepe porro odit inventore? Consectetur, dolore? Exercitationem vel asperiores natus quae expedita, vitae eius, reiciendis laboriosam quis explicabo amet veritatis perspiciatis magni voluptatibus? Praesentium neque optio unde vitae consequatur! Eius laborum dignissimos sapiente deserunt ipsam, neque similique. Accusantium fugiat corporis laborum cupiditate maxime fugit quasi veritatis!
                </p>
            </div>
        </Card>
    )
}
